### ISSUE TITLE
setCountTopSpaces() wrong behaviour when child section

### ISSUE THREAD

**Issue by Osiris-Team** [Osiris-Team/Dyml#19]
Example:
```java
        yaml.put("g0", "g1a", "g2a").setCountTopSpaces(1).setDefValues("wow!");
```
Output:
```yaml

g0: 

  g1a: 

    g2a: wow!
```
Instead of:
```yaml
g0: 
  g1a: 

    g2a: wow!
```
