### ISSUE TITLE
Rewrite Yaml classes (remove list based design)

### ISSUE THREAD

**Issue by Osiris-Team** [Osiris-Team/Dyml#26]
So that something like this is possible:
```yaml
key1:
  child1:
    child2: value
```
```java
Yaml child1 = yaml.get("key1", "child1");
child1.get("child2").asString();
```
